spring:
    datasource:
       driver-calss-name: com.mysql.jdbc.Driver    #驱动类
       url: jdbc:mysql://127.0.0.1:3306/springcloud?buseUnicode=true&amp;characterEncoding=UTF-8        #数据库地址
       username: root
       password: 123456
    jpa:
        hibernate:
          ddl-auto: update
        show-sql:  true
    thymeleaf:
        cache: false
logging:
    level:
        org:
           springframework:
                  security:  INFO
